/* written by client - calls client stub, xdr client, xdr xerver, server stub, server routine */ 

#include "avg.h"	/* header file generated by rpcgen */ 
#include <stdlib.h>
#include <string.h>

/* local routine client */
/* prototype can be whatever you want */
void averageprog_1( char* host, int argc, char *argv[] )
{
	CLIENT *clnt; /* client handle, rpc.h included in avg.h from rpcgen */
	int i;
	char * result_1;
	input_data average_1_arg;

	average_1_arg.input_data.input_data_val = (char*) malloc(MAXAVGSIZE*sizeof(char));

	//Length calculates how long the echoed string will be
	//The +1 accounts for the spaces between words
	int length = 0;
	for (i = 2; i <= (argc-1); i++)
	{
		length += strlen(argv[i])+1;
	}

	average_1_arg.input_data.input_data_len = length;

	//Storing the values from argv in a string with each word separated by a space
	char inputstr[length];
	int offset = 0;   
	char * space = " ";
	offset = snprintf(inputstr,strlen(argv[2])+1,"%s",argv[2]);
	for ( i = 3; i <= (argc-1); i++)
	{
		//printf("String is %s\n",inputstr);
		offset += snprintf(inputstr+offset, 2, "%s", space);
		offset += snprintf(inputstr+offset,strlen(argv[i])+1,"%s",argv[i]);	
	}
	printf("String is %s\n",inputstr);
	clnt = clnt_create( host, AVERAGEPROG, AVERAGEVERS, "udp" );

	average_1_arg.input_data.input_data_val = inputstr;

	/* check if error */
	if (clnt == NULL) 
	{
		/* 
		* rpc error library routine
		*  print a more descriptive error 
		*/
		clnt_pcreateerror( host );
		exit(1);
	}

	//Call the server
	average_1_arg = *average_1( &average_1_arg, clnt );

	if (average_1_arg.input_data.input_data_val == NULL) 
	{
		clnt_perror(clnt, "call failed:");
	}

	clnt_destroy( clnt );

	printf( "Echoed string is: %s\n",average_1_arg.input_data.input_data_val);
}


/* here is main */
main( int argc, char* argv[] )
{
	char *host;

	/* check correct syntax */
	if( argc < 3 )
	{
		printf( "usage: %s server_host value ...\n", argv[0]); 
		exit(1);
	}
	int length = 0;
	int i;
	//The index for this loop starts at 2 since indices 0 and 1 are the program name and IP respectively
        for (i = 2; i <= (argc-1); i++)
        {
                length += strlen(argv[i])+1;
        }
	if (length > MAXAVGSIZE)
	{
		printf("The input string is too long, it needs to be less than %i chars including spaces\n",MAXAVGSIZE);
		exit(1);
	}

	host = argv[1];
	averageprog_1( host, argc, argv);
}
